version: "3.5"
services:
  serverdb:
    image: "mysql"
    env_file:
     - "./be/.env"
    volumes:
      - "quizdb:/var/lib/mysql"

  server:
    env_file:
     - "./be/.env"
    build:
      context: "./be"
    volumes:
      - "./be/package:/package"
    ports:
      - "5500:5500"
    stdin_open: true
    tty: true

volumes:
  quizdb:
  cache:
