version: "3.5"
services:
  serverdb:
    image: "mysql"
    env_file:
     - ".env"
    volumes:
      - "interviewdb:/var/lib/mysql"

  server:
    env_file:
     - ".env"
    build:
      context: "./"
    volumes:
      - "./package:/package"
    ports:
      - "5500:5500"


volumes:
  interviewdb:
