version: "3.5"
services:
  serverdb:
    image: "postgres:13.1-alpine"
    env_file:
      - ".env"
    volumes:
      - "interviewdb:/var/lib/postgresql/data"
    ports:
      - "4432:5432"

  server:
#    env_file:
#      - ".env"
    build:
      context: "./"
    volumes:
      - "./package:/package"
    ports:
      - "5500:5500"


volumes:
  interviewdb:
